language: node_js
node_js:
  - "node"
before-install:
  - npm install -g nodemon
install:
  - npm install 
cache:
  directories:
    - "node_modules"
cache: npm
script: nodemon --ignore app/ app.js
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true