sudo: required
language: node_js
node_js:
    - node
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_fb487ff84b7b_key -iv $encrypted_fb487ff84b7b_iv
      -in hack-points-241209ef6978.json.enc -out hack-points-241209ef6978.json
      -d
    - docker pull carlad/sinatra
    - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra;
      bundle exec foreman start;"
    - docker ps -a
    - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
deploy:
    keyfile: hack-points-241209ef6978.json
    provider: gae
    project: hack-points
    no_promote: true
