language: node_js
node_js:
- "node"
cache:
  directories:
    - "node_modules"
cache: npm
script: npm run build
env:
global:
    secure: <this is your encrypted NOW token. It was added when you ran travis encrypt>