sudo: required
language: node_js
node_js:
    - node
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_c969e5736884_key -iv $encrypted_c969e5736884_iv
      -in hack-points-241209ef6978.json.enc -out hack-points-241209ef6978.json -d

deploy:
    keyfile: hack-points-241209ef6978.json
    provider: gae
    project: hack-points
    no_promote: true
